$w1 = ~/core/media/wallpapers/green-wall.jpg
$w2 = ~/core/media/wallpapers/big-blue.jpg
$w3 = ~/core/media/wallpapers/ash-texture.jpg
$w4 = ~/core/media/wallpapers/yellow-lego.jpg
$w5 = ~/core/media/wallpapers/stripped-blue-wall.jpg
$w6 = ~/core/media/wallpapers/mountain-lake.png
$w7 = ~/core/media/wallpapers/cat.png
$w8 = ~/core/media/wallpapers/bridge-lake.jpg
$w9 = ~/core/media/wallpapers/mountain-painting.png

#preload =  $w1
#preload = $w2
#preload = $w3
#preload = $w4
preload = $w5
preload = $w6
preload = $w7
preload = $w8
preload = $w9

wallpaper = eDP-1, $w8

splash = false

#fully disable ipc
ipc = on


